version: '3'
services:

  postgres-service:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}